// <auto-generated />
namespace SMART.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20181017002_WMS_Move_Record : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20181017002_WMS_Move_Record));
        
        string IMigrationMetadata.Id
        {
            get { return "201810170844319_20181017002_WMS_Move_Record"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
