// <auto-generated />
namespace SMART.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20181018004_WMS_Stock_Task : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20181018004_WMS_Stock_Task));
        
        string IMigrationMetadata.Id
        {
            get { return "201810180918318_20181018004_WMS_Stock_Task"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
