// <auto-generated />
namespace SMART.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20181018001_WMS_Location : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20181018001_WMS_Location));
        
        string IMigrationMetadata.Id
        {
            get { return "201810180117183_20181018001_WMS_Location"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
